version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - database:/var/lib/postgresql/data
  app:
    image: purpleplum-node-app
    ports:
      - 13000:7000
    environment:
      POSTGRES_HOST: db

volumes:
  database:
